// Copyright 2011 Boris Kogan (boris@thekogans.net)
//
// This file is part of libthekogans_mex_3ds_io.
//
// libthekogans_mex_3ds_io is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// libthekogans_mex_3ds_io is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with libthekogans_mex_3ds_io. If not, see <http://www.gnu.org/licenses/>.

#include <algorithm>
#include "thekogans/mex/3ds/io/ChunkTypes.h"
#include "thekogans/mex/3ds/io/Util.h"

namespace thekogans {
    namespace mex {
        namespace _3ds {
            namespace io {

                void ReadColor (Color &color, ChunkReader &mainChunk) {
                    {
                        ChunkReader chunk (mainChunk);
                        if (chunk.GetID () == COLOR_24) {
                            color.gammaCorrected.type = Color::Parts::UI8_COLOR;
                            chunk >> color.gammaCorrected.byteColor.r >>
                                color.gammaCorrected.byteColor.g >> color.gammaCorrected.byteColor.b;
                        }
                        else if (chunk.GetID () == COLOR_F) {
                            color.gammaCorrected.type = Color::Parts::F32_COLOR;
                            chunk >> color.gammaCorrected.floatColor.r >>
                                color.gammaCorrected.floatColor.g >> color.gammaCorrected.floatColor.b;
                        }
                        else {
                            color.gammaCorrected.type = Color::Parts::NO_COLOR;
                            chunk.Rewind ();
                            chunk.HandleUknownChunk ("Util", "ReadColor-first");
                        }
                    }

                    {
                        ChunkReader chunk (mainChunk);
                        if (chunk.GetID () == LIN_COLOR_24) {
                            color.raw.type = Color::Parts::UI8_COLOR;
                            chunk >> color.raw.byteColor.r >>
                                color.raw.byteColor.g >> color.raw.byteColor.b;
                        }
                        else if (chunk.GetID () == LIN_COLOR_F) {
                            color.raw.type = Color::Parts::F32_COLOR;
                            chunk >> color.raw.floatColor.r >>
                                color.raw.floatColor.g >> color.raw.floatColor.b;
                        }
                        else {
                            color.raw.type = Color::Parts::NO_COLOR;
                            chunk.Rewind ();
                            // FIXME: I don't think this is necessary. Second
                            // chunk is not strictly necessary. It was added
                            // in later releases, and might actually be missing
                            // in some earlier versions of files.
                            // chunk.HandleUknownChunk ("Util", "ReadColor-second");
                        }
                    }
                }

                namespace {
                    struct ChunkIDName {
                        util::ui16 id;
                        const char *name;
                    } const chunkTable[] = {
                        {M3D_VERSION, "M3D_VERSION"},
                        {COLOR_F, "COLOR_F"},
                        {COLOR_24, "COLOR_24"},
                        {LIN_COLOR_24, "LIN_COLOR_24"},
                        {LIN_COLOR_F, "LIN_COLOR_F"},
                        {INT_PERCENTAGE, "INT_PERCENTAGE"},
                        {FLOAT_PERCENTAGE, "FLOAT_PERCENTAGE"},
                        {MASTER_SCALE, "MASTER_SCALE"},
                        {BIT_MAP, "BIT_MAP"},
                        {USE_BIT_MAP, "USE_BIT_MAP"},
                        {SOLID_BGND, "SOLID_BGND"},
                        {USE_SOLID_BGND, "USE_SOLID_BGND"},
                        {V_GRADIENT, "V_GRADIENT"},
                        {USE_V_GRADIENT, "USE_V_GRADIENT"},
                        {LO_SHADOW_BIAS, "LO_SHADOW_BIAS"},
                        {HI_SHADOW_BIAS, "HI_SHADOW_BIAS"},
                        {SHADOW_MAP_SIZE, "SHADOW_MAP_SIZE"},
                        {SHADOW_SAMPLES, "SHADOW_SAMPLES"},
                        {SHADOW_RANGE, "SHADOW_RANGE"},
                        {SHADOW_FILTER, "SHADOW_FILTER"},
                        {RAY_BIAS, "RAY_BIAS"},
                        {O_CONSTS, "O_CONSTS"},
                        {AMBIENT_LIGHT, "AMBIENT_LIGHT"},
                        {FOG, "FOG"},
                        {USE_FOG, "USE_FOG"},
                        {FOG_BGND, "FOG_BGND"},
                        {DISTANCE_CUE, "DISTANCE_CUE"},
                        {USE_DISTANCE_CUE, "USE_DISTANCE_CUE"},
                        {LAYER_FOG, "LAYER_FOG"},
                        {USE_LAYER_FOG, "USE_LAYER_FOG"},
                        {DCUE_BGND, "DCUE_BGND"},
                        {SMAGIC, "SMAGIC"},
                        {LMAGIC, "LMAGIC"},
                        {DEFAULT_VIEW, "DEFAULT_VIEW"},
                        {VIEW_TOP, "VIEW_TOP"},
                        {VIEW_BOTTOM, "VIEW_BOTTOM"},
                        {VIEW_LEFT, "VIEW_LEFT"},
                        {VIEW_RIGHT, "VIEW_RIGHT"},
                        {VIEW_FRONT, "VIEW_FRONT"},
                        {VIEW_BACK, "VIEW_BACK"},
                        {VIEW_USER, "VIEW_USER"},
                        {VIEW_CAMERA, "VIEW_CAMERA"},
                        {MDATA, "MDATA"},
                        {MESH_VERSION, "MESH_VERSION"},
                        {MLIBMAGIC, "MLIBMAGIC"},
                        {NAMED_OBJECT, "NAMED_OBJECT"},
                        {OBJ_HIDDEN, "OBJ_HIDDEN"},
                        {OBJ_VIS_LOFTER, "OBJ_VIS_LOFTER"},
                        {OBJ_DOESNT_CAST, "OBJ_DOESNT_CAST"},
                        {OBJ_MATTE, "OBJ_MATTE"},
                        {OBJ_FAST, "OBJ_FAST"},
                        {OBJ_PROCEDURAL, "OBJ_PROCEDURAL"},
                        {OBJ_FROZEN, "OBJ_FROZEN"},
                        {OBJ_DONT_RCVSHADOW, "OBJ_DONT_RCVSHADOW"},
                        {N_TRI_OBJECT, "N_TRI_OBJECT"},
                        {POINT_ARRAY, "POINT_ARRAY"},
                        {POINT_FLAG_ARRAY, "POINT_FLAG_ARRAY"},
                        {EDGE_ARRAY, "EDGE_ARRAY"},
                        {FACE_ARRAY, "FACE_ARRAY"},
                        {MSH_MAT_GROUP, "MSH_MAT_GROUP"},
                        {TEX_VERTS, "TEX_VERTS"},
                        {NORMALS, "NORMALS"},
                        {VERTEX_NORMALS, "VERTEX_NORMALS"},
                        {VERTEX_NORMAL, "VERTEX_NORMAL"},
                        {VERTEX_NORMALS2, "VERTEX_NORMALS2"},
                        {FACE_NORMALS, "FACE_NORMALS"},
                        {SMOOTH_GROUP, "SMOOTH_GROUP"},
                        {MESH_MATRIX, "MESH_MATRIX"},
                        {MESH_COLOR, "MESH_COLOR"},
                        {MESH_TEXTURE_INFO, "MESH_TEXTURE_INFO"},
                        {PROC_NAME, "PROC_NAME"},
                        {PROC_DATA, "PROC_DATA"},
                        {MSH_BOXMAP, "MSH_BOXMAP"},
                        {N_DIRECT_LIGHT, "N_DIRECT_LIGHT"},
                        {DL_SPOTLIGHT, "DL_SPOTLIGHT"},
                        {DL_OFF, "DL_OFF"},
                        {DL_ATTENUATE, "DL_ATTENUATE"},
                        {DL_RAYSHAD, "DL_RAYSHAD"},
                        {DL_SHADOWED, "DL_SHADOWED"},
                        {DL_LOCAL_SHADOW2, "DL_LOCAL_SHADOW2"},
                        {DL_SEE_CONE, "DL_SEE_CONE"},
                        {DL_SPOT_RECTANGULAR, "DL_SPOT_RECTANGULAR"},
                        {DL_SPOT_OVERSHOOT, "DL_SPOT_OVERSHOOT"},
                        {DL_PROJECTOR, "DL_PROJECTOR"},
                        {DL_EXCLUDE, "DL_EXCLUDE"},
                        {DL_RANGE, "DL_RANGE"},
                        {DL_SPOT_ROLL, "DL_SPOT_ROLL"},
                        {DL_SPOT_ASPECT, "DL_SPOT_ASPECT"},
                        {DL_RAY_BIAS, "DL_RAY_BIAS"},
                        {DL_INNER_RANGE, "DL_INNER_RANGE"},
                        {DL_OUTER_RANGE, "DL_OUTER_RANGE"},
                        {DL_MULTIPLIER, "DL_MULTIPLIER"},
                        {N_CAMERA, "N_CAMERA"},
                        {CAM_SEE_CONE, "CAM_SEE_CONE"},
                        {CAM_RANGES, "CAM_RANGES"},
                        {M3DMAGIC, "M3DMAGIC"},
                        {POLY_2D, "POLY_2D"},
                        {SHAPE_OK, "SHAPE_OK"},
                        {SHAPE_NOT_OK, "SHAPE_NOT_OK"},
                        {SHAPE_HOOK, "SHAPE_HOOK"},
                        {PATH_3D, "PATH_3D"},
                        {PATH_MATRIX, "PATH_MATRIX"},
                        {SHAPE_2D, "SHAPE_2D"},
                        {M_SCALE, "M_SCALE"},
                        {M_TWIST, "M_TWIST"},
                        {M_TEETER, "M_TEETER"},
                        {M_FIT, "M_FIT"},
                        {M_BEVEL, "M_BEVEL"},
                        {XZ_CURVE, "XZ_CURVE"},
                        {YZ_CURVE, "YZ_CURVE"},
                        {INTERPCT, "INTERPCT"},
                        {DEFORM_LIMIT, "DEFORM_LIMIT"},
                        {USE_CONTOUR, "USE_CONTOUR"},
                        {USE_TWEEN, "USE_TWEEN"},
                        {USE_SCALE, "USE_SCALE"},
                        {USE_TWIST, "USE_TWIST"},
                        {USE_TEETER, "USE_TEETER"},
                        {USE_FIT, "USE_FIT"},
                        {USE_BEVEL, "USE_BEVEL"},
                        {VIEWPORT_LAYOUT, "VIEWPORT_LAYOUT"},
                        {VIEWPORT_DATA, "VIEWPORT_DATA"},
                        {VIEWPORT_DATA_3, "VIEWPORT_DATA_3"},
                        {VIEWPORT_SIZE, "VIEWPORT_SIZE"},
                        {XDATA_SECTION, "XDATA_SECTION"},
                        {MAT_NAME, "MAT_NAME"},
                        {MAT_AMBIENT, "MAT_AMBIENT"},
                        {MAT_DIFFUSE, "MAT_DIFFUSE"},
                        {MAT_SPECULAR, "MAT_SPECULAR"},
                        {MAT_SHININESS, "MAT_SHININESS"},
                        {MAT_SHIN2PCT, "MAT_SHIN2PCT"},
                        {MAT_SHIN3PCT, "MAT_SHIN3PCT"},
                        {MAT_TRANSPARENCY, "MAT_TRANSPARENCY"},
                        {MAT_XPFALL, "MAT_XPFALL"},
                        {MAT_REFBLUR, "MAT_REFBLUR"},
                        {MAT_SELF_ILLUM, "MAT_SELF_ILLUM"},
                        {MAT_TWO_SIDE, "MAT_TWO_SIDE"},
                        {MAT_DECAL, "MAT_DECAL"},
                        {MAT_ADDITIVE, "MAT_ADDITIVE"},
                        {MAT_SELF_ILPCT, "MAT_SELF_ILPCT"},
                        {MAT_WIRE, "MAT_WIRE"},
                        {MAT_SUPERSMP, "MAT_SUPERSMP"},
                        {MAT_WIRESIZE, "MAT_WIRESIZE"},
                        {MAT_FACEMAP, "MAT_FACEMAP"},
                        {MAT_XPFALLIN, "MAT_XPFALLIN"},
                        {MAT_PHONGSOFT, "MAT_PHONGSOFT"},
                        {MAT_WIREABS, "MAT_WIREABS"},
                        {MAT_SHADING, "MAT_SHADING"},
                        {MAT_TEXMAP, "MAT_TEXMAP"},
                        {MAT_SPECMAP, "MAT_SPECMAP"},
                        {MAT_OPACMAP, "MAT_OPACMAP"},
                        {MAT_REFLMAP, "MAT_REFLMAP"},
                        {MAT_BUMPMAP, "MAT_BUMPMAP"},
                        {MAT_USE_XPFALL, "MAT_USE_XPFALL"},
                        {MAT_USE_REFBLUR, "MAT_USE_REFBLUR"},
                        {MAT_BUMP_PERCENT, "MAT_BUMP_PERCENT"},
                        {MAT_MAPNAME, "MAT_MAPNAME"},
                        {MAT_ACUBIC, "MAT_ACUBIC"},
                        {MAT_SXP_TEXT_DATA, "MAT_SXP_TEXT_DATA"},
                        {MAT_SXP_TEXT2_DATA, "MAT_SXP_TEXT2_DATA"},
                        {MAT_SXP_OPAC_DATA, "MAT_SXP_OPAC_DATA"},
                        {MAT_SXP_BUMP_DATA, "MAT_SXP_BUMP_DATA"},
                        {MAT_SXP_SPEC_DATA, "MAT_SXP_SPEC_DATA"},
                        {MAT_SXP_SHIN_DATA, "MAT_SXP_SHIN_DATA"},
                        {MAT_SXP_SELFI_DATA, "MAT_SXP_SELFI_DATA"},
                        {MAT_SXP_TEXT_MASKDATA, "MAT_SXP_TEXT_MASKDATA"},
                        {MAT_SXP_TEXT2_MASKDATA, "MAT_SXP_TEXT2_MASKDATA"},
                        {MAT_SXP_OPAC_MASKDATA, "MAT_SXP_OPAC_MASKDATA"},
                        {MAT_SXP_BUMP_MASKDATA, "MAT_SXP_BUMP_MASKDATA"},
                        {MAT_SXP_SPEC_MASKDATA, "MAT_SXP_SPEC_MASKDATA"},
                        {MAT_SXP_SHIN_MASKDATA, "MAT_SXP_SHIN_MASKDATA"},
                        {MAT_SXP_SELFI_MASKDATA, "MAT_SXP_SELFI_MASKDATA"},
                        {MAT_SXP_REFL_MASKDATA, "MAT_SXP_REFL_MASKDATA"},
                        {MAT_TEX2MAP, "MAT_TEX2MAP"},
                        {MAT_SHINMAP, "MAT_SHINMAP"},
                        {MAT_SELFIMAP, "MAT_SELFIMAP"},
                        {MAT_TEXMASK, "MAT_TEXMASK"},
                        {MAT_TEX2MASK, "MAT_TEX2MASK"},
                        {MAT_OPACMASK, "MAT_OPACMASK"},
                        {MAT_BUMPMASK, "MAT_BUMPMASK"},
                        {MAT_SHINMASK, "MAT_SHINMASK"},
                        {MAT_SPECMASK, "MAT_SPECMASK"},
                        {MAT_SELFIMASK, "MAT_SELFIMASK"},
                        {MAT_REFLMASK, "MAT_REFLMASK"},
                        {MAT_MAP_TILINGOLD, "MAT_MAP_TILINGOLD"},
                        {MAT_MAP_TILING, "MAT_MAP_TILING"},
                        {MAT_MAP_TEXBLUR_OLD, "MAT_MAP_TEXBLUR_OLD"},
                        {MAT_MAP_TEXBLUR, "MAT_MAP_TEXBLUR"},
                        {MAT_MAP_USCALE, "MAT_MAP_USCALE"},
                        {MAT_MAP_VSCALE, "MAT_MAP_VSCALE"},
                        {MAT_MAP_UOFFSET, "MAT_MAP_UOFFSET"},
                        {MAT_MAP_VOFFSET, "MAT_MAP_VOFFSET"},
                        {MAT_MAP_ANG, "MAT_MAP_ANG"},
                        {MAT_MAP_COL1, "MAT_MAP_COL1"},
                        {MAT_MAP_COL2, "MAT_MAP_COL2"},
                        {MAT_MAP_RCOL, "MAT_MAP_RCOL"},
                        {MAT_MAP_GCOL, "MAT_MAP_GCOL"},
                        {MAT_MAP_BCOL, "MAT_MAP_BCOL"},
                        {MAT_ENTRY, "MAT_ENTRY"},
                        {KFDATA, "KFDATA"},
                        {AMBIENT_NODE_TAG, "AMBIENT_NODE_TAG"},
                        {OBJECT_NODE_TAG, "OBJECT_NODE_TAG"},
                        {CAMERA_NODE_TAG, "CAMERA_NODE_TAG"},
                        {TARGET_NODE_TAG, "TARGET_NODE_TAG"},
                        {LIGHT_NODE_TAG, "LIGHT_NODE_TAG"},
                        {L_TARGET_NODE_TAG, "L_TARGET_NODE_TAG"},
                        {SPOTLIGHT_NODE_TAG, "SPOTLIGHT_NODE_TAG"},
                        {KFSEG, "KFSEG"},
                        {KFCURTIME, "KFCURTIME"},
                        {KFHDR, "KFHDR"},
                        {NODE_HDR, "NODE_HDR"},
                        {INSTANCE_NAME, "INSTANCE_NAME"},
                        {PRESCALE, "PRESCALE"},
                        {PIVOT, "PIVOT"},
                        {BOUNDBOX, "BOUNDBOX"},
                        {MORPH_SMOOTH, "MORPH_SMOOTH"},
                        {POS_TRACK_TAG, "POS_TRACK_TAG"},
                        {ROT_TRACK_TAG, "ROT_TRACK_TAG"},
                        {SCL_TRACK_TAG, "SCL_TRACK_TAG"},
                        {FOV_TRACK_TAG, "FOV_TRACK_TAG"},
                        {ROLL_TRACK_TAG, "ROLL_TRACK_TAG"},
                        {COL_TRACK_TAG, "COL_TRACK_TAG"},
                        {MORPH_TRACK_TAG, "MORPH_TRACK_TAG"},
                        {HOT_TRACK_TAG, "HOT_TRACK_TAG"},
                        {FALL_TRACK_TAG, "FALL_TRACK_TAG"},
                        {HIDE_TRACK_TAG, "HIDE_TRACK_TAG"},
                        {NODE_ID, "NODE_ID"},
                        {C_MDRAWER, "C_MDRAWER"},
                        {C_TDRAWER, "C_TDRAWER"},
                        {C_SHPDRAWER, "C_SHPDRAWER"},
                        {C_MODDRAWER, "C_MODDRAWER"},
                        {C_RIPDRAWER, "C_RIPDRAWER"},
                        {C_TXDRAWER, "C_TXDRAWER"},
                        {C_PDRAWER, "C_PDRAWER"},
                        {C_MTLDRAWER, "C_MTLDRAWER"},
                        {C_FLIDRAWER, "C_FLIDRAWER"},
                        {C_CUBDRAWER, "C_CUBDRAWER"},
                        {C_MFILE, "C_MFILE"},
                        {C_SHPFILE, "C_SHPFILE"},
                        {C_MODFILE, "C_MODFILE"},
                        {C_RIPFILE, "C_RIPFILE"},
                        {C_TXFILE, "C_TXFILE"},
                        {C_PFILE, "C_PFILE"},
                        {C_MTLFILE, "C_MTLFILE"},
                        {C_FLIFILE, "C_FLIFILE"},
                        {C_PALFILE, "C_PALFILE"},
                        {C_TX_STRING, "C_TX_STRING"},
                        {C_CONSTS, "C_CONSTS"},
                        {C_SNAPS, "C_SNAPS"},
                        {C_GRIDS, "C_GRIDS"},
                        {C_ASNAPS, "C_ASNAPS"},
                        {C_GRID_RANGE, "C_GRID_RANGE"},
                        {C_RENDTYPE, "C_RENDTYPE"},
                        {C_PROGMODE, "C_PROGMODE"},
                        {C_PREVMODE, "C_PREVMODE"},
                        {C_MODWMODE, "C_MODWMODE"},
                        {C_MODMODEL, "C_MODMODEL"},
                        {C_ALL_LINES, "C_ALL_LINES"},
                        {C_BACK_TYPE, "C_BACK_TYPE"},
                        {C_MD_CS, "C_MD_CS"},
                        {C_MD_CE, "C_MD_CE"},
                        {C_MD_SML, "C_MD_SML"},
                        {C_MD_SMW, "C_MD_SMW"},
                        {C_LOFT_WITH_TEXTURE, "C_LOFT_WITH_TEXTURE"},
                        {C_LOFT_L_REPEAT, "C_LOFT_L_REPEAT"},
                        {C_LOFT_W_REPEAT, "C_LOFT_W_REPEAT"},
                        {C_LOFT_UV_NORMALIZE, "C_LOFT_UV_NORMALIZE"},
                        {C_WELD_LOFT, "C_WELD_LOFT"},
                        {C_MD_PDET, "C_MD_PDET"},
                        {C_MD_SDET, "C_MD_SDET"},
                        {C_RGB_RMODE, "C_RGB_RMODE"},
                        {C_RGB_HIDE, "C_RGB_HIDE"},
                        {C_RGB_MAPSW, "C_RGB_MAPSW"},
                        {C_RGB_TWOSIDE, "C_RGB_TWOSIDE"},
                        {C_RGB_SHADOW, "C_RGB_SHADOW"},
                        {C_RGB_AA, "C_RGB_AA"},
                        {C_RGB_OVW, "C_RGB_OVW"},
                        {C_RGB_OVH, "C_RGB_OVH"},
                        {CMAGIC, "CMAGIC"},
                        {C_RGB_PICTYPE, "C_RGB_PICTYPE"},
                        {C_RGB_OUTPUT, "C_RGB_OUTPUT"},
                        {C_RGB_TODISK, "C_RGB_TODISK"},
                        {C_RGB_COMPRESS, "C_RGB_COMPRESS"},
                        {C_JPEG_COMPRESSION, "C_JPEG_COMPRESSION"},
                        {C_RGB_DISPDEV, "C_RGB_DISPDEV"},
                        {C_RGB_HARDDEV, "C_RGB_HARDDEV"},
                        {C_RGB_PATH, "C_RGB_PATH"},
                        {C_BITMAP_DRAWER, "C_BITMAP_DRAWER"},
                        {C_RGB_FILE, "C_RGB_FILE"},
                        {C_RGB_OVASPECT, "C_RGB_OVASPECT"},
                        {C_RGB_ANIMTYPE, "C_RGB_ANIMTYPE"},
                        {C_RENDER_ALL, "C_RENDER_ALL"},
                        {C_REND_FROM, "C_REND_FROM"},
                        {C_REND_TO, "C_REND_TO"},
                        {C_REND_NTH, "C_REND_NTH"},
                        {C_PAL_TYPE, "C_PAL_TYPE"},
                        {C_RND_TURBO, "C_RND_TURBO"},
                        {C_RND_MIP, "C_RND_MIP"},
                        {C_BGND_METHOD, "C_BGND_METHOD"},
                        {C_AUTO_REFLECT, "C_AUTO_REFLECT"},
                        {C_VP_FROM, "C_VP_FROM"},
                        {C_VP_TO, "C_VP_TO"},
                        {C_VP_NTH, "C_VP_NTH"},
                        {C_REND_TSTEP, "C_REND_TSTEP"},
                        {C_VP_TSTEP, "C_VP_TSTEP"},
                        {C_SRDIAM, "C_SRDIAM"},
                        {C_SRDEG, "C_SRDEG"},
                        {C_SRSEG, "C_SRSEG"},
                        {C_SRDIR, "C_SRDIR"},
                        {C_HETOP, "C_HETOP"},
                        {C_HEBOT, "C_HEBOT"},
                        {C_HEHT, "C_HEHT"},
                        {C_HETURNS, "C_HETURNS"},
                        {C_HEDEG, "C_HEDEG"},
                        {C_HESEG, "C_HESEG"},
                        {C_HEDIR, "C_HEDIR"},
                        {C_QUIKSTUFF, "C_QUIKSTUFF"},
                        {C_SEE_LIGHTS, "C_SEE_LIGHTS"},
                        {C_SEE_CAMERAS, "C_SEE_CAMERAS"},
                        {C_SEE_3D, "C_SEE_3D"},
                        {C_MESHSEL, "C_MESHSEL"},
                        {C_MESHUNSEL, "C_MESHUNSEL"},
                        {C_POLYSEL, "C_POLYSEL"},
                        {C_POLYUNSEL, "C_POLYUNSEL"},
                        {C_SHPLOCAL, "C_SHPLOCAL"},
                        {C_MSHLOCAL, "C_MSHLOCAL"},
                        {C_NUM_FORMAT, "C_NUM_FORMAT"},
                        {C_ARCH_DENOM, "C_ARCH_DENOM"},
                        {C_IN_DEVICE, "C_IN_DEVICE"},
                        {C_MSCALE, "C_MSCALE"},
                        {C_COMM_PORT, "C_COMM_PORT"},
                        {C_TAB_BASES, "C_TAB_BASES"},
                        {C_TAB_DIVS, "C_TAB_DIVS"},
                        {C_MASTER_SCALES, "C_MASTER_SCALES"},
                        {C_SHOW_1STVERT, "C_SHOW_1STVERT"},
                        {C_SHAPER_OK, "C_SHAPER_OK"},
                        {C_LOFTER_OK, "C_LOFTER_OK"},
                        {C_EDITOR_OK, "C_EDITOR_OK"},
                        {C_KEYFRAMER_OK, "C_KEYFRAMER_OK"},
                        {C_PICKSIZE, "C_PICKSIZE"},
                        {C_MAPTYPE, "C_MAPTYPE"},
                        {C_MAP_DISPLAY, "C_MAP_DISPLAY"},
                        {C_TILE_XY, "C_TILE_XY"},
                        {C_MAP_XYZ, "C_MAP_XYZ"},
                        {C_MAP_SCALE, "C_MAP_SCALE"},
                        {C_MAP_MATRIX_OLD, "C_MAP_MATRIX_OLD"},
                        {C_MAP_MATRIX, "C_MAP_MATRIX"},
                        {C_MAP_WID_HT, "C_MAP_WID_HT"},
                        {C_OBNAME, "C_OBNAME"},
                        {C_CAMNAME, "C_CAMNAME"},
                        {C_LTNAME, "C_LTNAME"},
                        {C_CUR_MNAME, "C_CUR_MNAME"},
                        {C_CURMTL_FROM_MESH, "C_CURMTL_FROM_MESH"},
                        {C_GET_SHAPE_MAKE_FACES, "C_GET_SHAPE_MAKE_FACES"},
                        {C_DETAIL, "C_DETAIL"},
                        {C_VERTMARK, "C_VERTMARK"},
                        {C_MSHAX, "C_MSHAX"},
                        {C_MSHCP, "C_MSHCP"},
                        {C_USERAX, "C_USERAX"},
                        {C_SHOOK, "C_SHOOK"},
                        {C_RAX, "C_RAX"},
                        {C_STAPE, "C_STAPE"},
                        {C_LTAPE, "C_LTAPE"},
                        {C_ETAPE, "C_ETAPE"},
                        {C_KTAPE, "C_KTAPE"},
                        {C_SPHSEGS, "C_SPHSEGS"},
                        {C_GEOSMOOTH, "C_GEOSMOOTH"},
                        {C_HEMISEGS, "C_HEMISEGS"},
                        {C_PRISMSEGS, "C_PRISMSEGS"},
                        {C_PRISMSIDES, "C_PRISMSIDES"},
                        {C_TUBESEGS, "C_TUBESEGS"},
                        {C_TUBESIDES, "C_TUBESIDES"},
                        {C_TORSEGS, "C_TORSEGS"},
                        {C_TORSIDES, "C_TORSIDES"},
                        {C_CONESIDES, "C_CONESIDES"},
                        {C_CONESEGS, "C_CONESEGS"},
                        {C_NGPARMS, "C_NGPARMS"},
                        {C_PTHLEVEL, "C_PTHLEVEL"},
                        {C_MSCSYM, "C_MSCSYM"},
                        {C_MFTSYM, "C_MFTSYM"},
                        {C_MTTSYM, "C_MTTSYM"},
                        {C_SMOOTHING, "C_SMOOTHING"},
                        {C_MODICOUNT, "C_MODICOUNT"},
                        {C_FONTSEL, "C_FONTSEL"},
                        {C_TESS_TYPE, "C_TESS_TYPE"},
                        {C_TESS_TENSION, "C_TESS_TENSION"},
                        {C_SEG_START, "C_SEG_START"},
                        {C_SEG_END, "C_SEG_END"},
                        {C_CURTIME, "C_CURTIME"},
                        {C_ANIMLENGTH, "C_ANIMLENGTH"},
                        {C_PV_FROM, "C_PV_FROM"},
                        {C_PV_TO, "C_PV_TO"},
                        {C_PV_DOFNUM, "C_PV_DOFNUM"},
                        {C_PV_RNG, "C_PV_RNG"},
                        {C_PV_NTH, "C_PV_NTH"},
                        {C_PV_TYPE, "C_PV_TYPE"},
                        {C_PV_METHOD, "C_PV_METHOD"},
                        {C_PV_FPS, "C_PV_FPS"},
                        {C_VTR_FRAMES, "C_VTR_FRAMES"},
                        {C_VTR_HDTL, "C_VTR_HDTL"},
                        {C_VTR_HD, "C_VTR_HD"},
                        {C_VTR_TL, "C_VTR_TL"},
                        {C_VTR_IN, "C_VTR_IN"},
                        {C_VTR_PK, "C_VTR_PK"},
                        {C_VTR_SH, "C_VTR_SH"},
                        {C_WORK_MTLS, "C_WORK_MTLS"},
                        {C_WORK_MTLS_2, "C_WORK_MTLS_2"},
                        {C_WORK_MTLS_3, "C_WORK_MTLS_3"},
                        {C_WORK_MTLS_4, "C_WORK_MTLS_4"},
                        {C_BGTYPE, "C_BGTYPE"},
                        {C_MEDTILE, "C_MEDTILE"},
                        {C_LO_CONTRAST, "C_LO_CONTRAST"},
                        {C_HI_CONTRAST, "C_HI_CONTRAST"},
                        {C_FROZ_DISPLAY, "C_FROZ_DISPLAY"},
                        {C_BOOLWELD, "C_BOOLWELD"},
                        {C_BOOLTYPE, "C_BOOLTYPE"},
                        {C_ANG_THRESH, "C_ANG_THRESH"},
                        {C_SS_THRESH, "C_SS_THRESH"},
                        {C_TEXTURE_BLUR_DEFAULT, "C_TEXTURE_BLUR_DEFAULT"},
                        {C_MAPDRAWER, "C_MAPDRAWER"},
                        {C_MAPDRAWER1, "C_MAPDRAWER1"},
                        {C_MAPDRAWER2, "C_MAPDRAWER2"},
                        {C_MAPDRAWER3, "C_MAPDRAWER3"},
                        {C_MAPDRAWER4, "C_MAPDRAWER4"},
                        {C_MAPDRAWER5, "C_MAPDRAWER5"},
                        {C_MAPDRAWER6, "C_MAPDRAWER6"},
                        {C_MAPDRAWER7, "C_MAPDRAWER7"},
                        {C_MAPDRAWER8, "C_MAPDRAWER8"},
                        {C_MAPDRAWER9, "C_MAPDRAWER9"},
                        {C_MAPDRAWER_ENTRY, "C_MAPDRAWER_ENTRY"},
                        {C_BACKUP_FILE, "C_BACKUP_FILE"},
                        {C_DITHER_256, "C_DITHER_256"},
                        {C_SAVE_LAST, "C_SAVE_LAST"},
                        {C_USE_ALPHA, "C_USE_ALPHA"},
                        {C_TGA_DEPTH, "C_TGA_DEPTH"},
                        {C_REND_FIELDS, "C_REND_FIELDS"},
                        {C_REFLIP, "C_REFLIP"},
                        {C_SEL_ITEMTOG, "C_SEL_ITEMTOG"},
                        {C_SEL_RESET, "C_SEL_RESET"},
                        {C_STICKY_KEYINF, "C_STICKY_KEYINF"},
                        {C_WELD_THRESHOLD, "C_WELD_THRESHOLD"},
                        {C_ZCLIP_POINT, "C_ZCLIP_POINT"},
                        {C_ALPHA_SPLIT, "C_ALPHA_SPLIT"},
                        {C_KF_SHOW_BACKFACE, "C_KF_SHOW_BACKFACE"},
                        {C_OPTIMIZE_LOFT, "C_OPTIMIZE_LOFT"},
                        {C_TENS_DEFAULT, "C_TENS_DEFAULT"},
                        {C_CONT_DEFAULT, "C_CONT_DEFAULT"},
                        {C_BIAS_DEFAULT, "C_BIAS_DEFAULT"},
                        {C_DXFNAME_SRC, "C_DXFNAME_SRC"},
                        {C_AUTO_WELD, "C_AUTO_WELD"},
                        {C_AUTO_UNIFY, "C_AUTO_UNIFY"},
                        {C_AUTO_SMOOTH, "C_AUTO_SMOOTH"},
                        {C_DXF_SMOOTH_ANG, "C_DXF_SMOOTH_ANG"},
                        {C_SMOOTH_ANG, "C_SMOOTH_ANG"},
                        {C_WORK_MTLS_5, "C_WORK_MTLS_5"},
                        {C_WORK_MTLS_6, "C_WORK_MTLS_6"},
                        {C_WORK_MTLS_7, "C_WORK_MTLS_7"},
                        {C_WORK_MTLS_8, "C_WORK_MTLS_8"},
                        {C_WORKMTL, "C_WORKMTL"},
                        {C_SXP_TEXT_DATA, "C_SXP_TEXT_DATA"},
                        {C_SXP_OPAC_DATA, "C_SXP_OPAC_DATA"},
                        {C_SXP_BUMP_DATA, "C_SXP_BUMP_DATA"},
                        {C_SXP_SHIN_DATA, "C_SXP_SHIN_DATA"},
                        {C_SXP_TEXT2_DATA, "C_SXP_TEXT2_DATA"},
                        {C_SXP_SPEC_DATA, "C_SXP_SPEC_DATA"},
                        {C_SXP_SELFI_DATA, "C_SXP_SELFI_DATA"},
                        {C_SXP_TEXT_MASKDATA, "C_SXP_TEXT_MASKDATA"},
                        {C_SXP_TEXT2_MASKDATA, "C_SXP_TEXT2_MASKDATA"},
                        {C_SXP_OPAC_MASKDATA, "C_SXP_OPAC_MASKDATA"},
                        {C_SXP_BUMP_MASKDATA, "C_SXP_BUMP_MASKDATA"},
                        {C_SXP_SPEC_MASKDATA, "C_SXP_SPEC_MASKDATA"},
                        {C_SXP_SHIN_MASKDATA, "C_SXP_SHIN_MASKDATA"},
                        {C_SXP_SELFI_MASKDATA, "C_SXP_SELFI_MASKDATA"},
                        {C_SXP_REFL_MASKDATA, "C_SXP_REFL_MASKDATA"},
                        {C_NET_USE_VPOST, "C_NET_USE_VPOST"},
                        {C_NET_USE_GAMMA, "C_NET_USE_GAMMA"},
                        {C_NET_FIELD_ORDER, "C_NET_FIELD_ORDER"},
                        {C_BLUR_FRAMES, "C_BLUR_FRAMES"},
                        {C_BLUR_SAMPLES, "C_BLUR_SAMPLES"},
                        {C_BLUR_DUR, "C_BLUR_DUR"},
                        {C_HOT_METHOD, "C_HOT_METHOD"},
                        {C_HOT_CHECK, "C_HOT_CHECK"},
                        {C_PIXEL_SIZE, "C_PIXEL_SIZE"},
                        {C_DISP_GAMMA, "C_DISP_GAMMA"},
                        {C_FBUF_GAMMA, "C_FBUF_GAMMA"},
                        {C_FILE_OUT_GAMMA, "C_FILE_OUT_GAMMA"},
                        {C_FILE_IN_GAMMA, "C_FILE_IN_GAMMA"},
                        {C_GAMMA_CORRECT, "C_GAMMA_CORRECT"},
                        {C_APPLY_DISP_GAMMA, "C_APPLY_DISP_GAMMA"},
                        {C_APPLY_FBUF_GAMMA, "C_APPLY_FBUF_GAMMA"},
                        {C_APPLY_FILE_GAMMA, "C_APPLY_FILE_GAMMA"},
                        {C_FORCE_WIRE, "C_FORCE_WIRE"},
                        {C_RAY_SHADOWS, "C_RAY_SHADOWS"},
                        {C_MASTER_AMBIENT, "C_MASTER_AMBIENT"},
                        {C_SUPER_SAMPLE, "C_SUPER_SAMPLE"},
                        {C_OBJECT_MBLUR, "C_OBJECT_MBLUR"},
                        {C_MBLUR_DITHER, "C_MBLUR_DITHER"},
                        {C_DITHER_24, "C_DITHER_24"},
                        {C_SUPER_BLACK, "C_SUPER_BLACK"},
                        {C_SAFE_FRAME, "C_SAFE_FRAME"},
                        {C_VIEW_PRES_RATIO, "C_VIEW_PRES_RATIO"},
                        {C_BGND_PRES_RATIO, "C_BGND_PRES_RATIO"},
                        {C_NTH_SERIAL_NUM, "C_NTH_SERIAL_NUM"},
                        {VPDATA, "VPDATA"},
                        {P_QUEUE_ENTRY, "P_QUEUE_ENTRY"},
                        {P_QUEUE_IMAGE, "P_QUEUE_IMAGE"},
                        {P_QUEUE_USEIGAMMA, "P_QUEUE_USEIGAMMA"},
                        {P_QUEUE_PROC, "P_QUEUE_PROC"},
                        {P_QUEUE_SOLID, "P_QUEUE_SOLID"},
                        {P_QUEUE_GRADIENT, "P_QUEUE_GRADIENT"},
                        {P_QUEUE_KF, "P_QUEUE_KF"},
                        {P_QUEUE_MOTBLUR, "P_QUEUE_MOTBLUR"},
                        {P_QUEUE_MB_REPEAT, "P_QUEUE_MB_REPEAT"},
                        {P_QUEUE_NONE, "P_QUEUE_NONE"},
                        {P_QUEUE_RESIZE, "P_QUEUE_RESIZE"},
                        {P_QUEUE_OFFSET, "P_QUEUE_OFFSET"},
                        {P_QUEUE_ALIGN, "P_QUEUE_ALIGN"},
                        {P_CUSTOM_SIZE, "P_CUSTOM_SIZE"},
                        {P_ALPH_NONE, "P_ALPH_NONE"},
                        {P_ALPH_PSEUDO, "P_ALPH_PSEUDO"},
                        {P_ALPH_OP_PSEUDO, "P_ALPH_OP_PSEUDO"},
                        {P_ALPH_BLUR, "P_ALPH_BLUR"},
                        {P_ALPH_PCOL, "P_ALPH_PCOL"},
                        {P_ALPH_C0, "P_ALPH_C0"},
                        {P_ALPH_OP_KEY, "P_ALPH_OP_KEY"},
                        {P_ALPH_KCOL, "P_ALPH_KCOL"},
                        {P_ALPH_OP_NOCONV, "P_ALPH_OP_NOCONV"},
                        {P_ALPH_IMAGE, "P_ALPH_IMAGE"},
                        {P_ALPH_ALPHA, "P_ALPH_ALPHA"},
                        {P_ALPH_QUES, "P_ALPH_QUES"},
                        {P_ALPH_QUEIMG, "P_ALPH_QUEIMG"},
                        {P_ALPH_CUTOFF, "P_ALPH_CUTOFF"},
                        {P_ALPHANEG, "P_ALPHANEG"},
                        {P_TRAN_NONE, "P_TRAN_NONE"},
                        {P_TRAN_IMAGE, "P_TRAN_IMAGE"},
                        {P_TRAN_FRAMES, "P_TRAN_FRAMES"},
                        {P_TRAN_FADEIN, "P_TRAN_FADEIN"},
                        {P_TRAN_FADEOUT, "P_TRAN_FADEOUT"},
                        {P_TRANNEG, "P_TRANNEG"},
                        {P_RANGES, "P_RANGES"},
                        {P_PROC_DATA, "P_PROC_DATA"}
                    };

                    const util::ui32 CHUNK_TABLE_SIZE = sizeof (chunkTable) / sizeof (chunkTable[0]);

                    struct CompareChunkIDName {
                        inline bool operator () (const ChunkIDName &value1, util::ui16 id) {
                            return value1.id < id;
                        }
                    };
                }

                _LIB_THEKOGANS_MEX_3DS_IO_DECL const char * _LIB_THEKOGANS_MEX_3DS_IO_API ChunkNameFromID (util::ui16 id) {
                    const ChunkIDName *result = std::lower_bound (chunkTable,
                        chunkTable + CHUNK_TABLE_SIZE, id, CompareChunkIDName ());
                    return result != 0 && result->id == id ? result->name : "";
                }

            } // namespace io
        } // namespace _3ds
    } // namespace mex
} // namespace thekogans
